In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

col_names=['pregnant','glucose','bp','shin','insulin','bmi','pedigree','age','label']
pima = pd.read_csv("3,4csv.csv", header = None, names = col_names)

In [2]:
pima.head()

   pregnant  glucose  bp  shin  insulin   bmi  pedigree  age  label
0         6      148  72    35        0  33.6     0.627   50      1
1         1       85  66    29        0  26.6     0.351   31      0
2         8      183  64     0        0  23.3     0.672   32      1
3         1       89  66    23       94  28.1     0.167   21      0
4         0      137  40    35      168  43.1     2.288   33      1

In [3]:
pima.sample(5)

     pregnant  glucose  bp  shin  insulin   bmi  pedigree  age  label
171         6      134  70    23      130  35.4     0.542   29      1
531         0      107  76     0        0  45.3     0.686   24      0
602         1      124  74    36        0  27.8     0.100   30      0
731         8      120  86     0        0  28.4     0.259   22      1
727         0      141  84    26        0  32.4     0.433   22      0

In [4]:
pima.tail()

     pregnant  glucose  bp  shin  insulin   bmi  pedigree  age  label
763        10      101  76    48      180  32.9     0.171   63      0
764         2      122  70    27        0  36.8     0.340   27      0
765         5      121  72    23      112  26.2     0.245   30      0
766         1      126  60     0        0  30.1     0.349   47      1
767         1       93  70    31        0  30.4     0.315   23      0

In [5]:
#split dataset in feature and target variable
feature_cols=['pregnant','insulin','bmi','age','glucose','bp','pedigree']
X=pima[feature_cols]# Feature
Y=pima.label # target variable

# split dataset inti training set and test set
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.3,random_state=1)# 70% training and 30% testing

# crete decision tree classifier object
clf = DecisionTreeClassifier()

# train decision tree classifier
clf =clf.fit(X_train,Y_train)

# predict the response for the test dataset
Y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_test, Y_pred))

Accuracy: 0.7012987012987013